"""
One-Click Setup Script for LLaMA 3 8B Medical RAG System
RTX 5060 Ti + Ryzen 7 5700X optimization
"""

import os
import sys
import subprocess
import platform
from pathlib import Path

def print_header():
    print("🦙" + "=" * 68 + "🦙")
    print("🔥 LLaMA 3 8B MEDICAL RAG SETUP")
    print("🎮 RTX 5060 Ti + Ryzen 7 5700X Optimization")
    print("🏥 One-Click Installation & Configuration")
    print("🦙" + "=" * 68 + "🦙")
    print()

def check_python_version():
    """Check Python version"""
    print("🐍 Checking Python version...")
    version = sys.version_info
    if version.major == 3 and version.minor >= 8:
        print(f"✅ Python {version.major}.{version.minor}.{version.micro} - Compatible")
        return True
    else:
        print(f"❌ Python {version.major}.{version.minor}.{version.micro} - Need Python 3.8+")
        return False

def check_cuda():
    """Check CUDA availability"""
    print("🔥 Checking CUDA installation...")
    try:
        import torch
        if torch.cuda.is_available():
            gpu_name = torch.cuda.get_device_name(0)
            gpu_memory = torch.cuda.get_device_properties(0).total_memory / (1024**3)
            print(f"✅ CUDA Available: {gpu_name} ({gpu_memory:.1f}GB)")
            if gpu_memory >= 12.0:
                print("🎮 GPU Memory: Perfect for LLaMA 3 8B")
            else:
                print("⚠️  GPU Memory: May be tight for LLaMA 3 8B")
            return True
        else:
            print("❌ CUDA not available - will use CPU mode")
            return False
    except ImportError:
        print("⚠️  PyTorch not installed yet")
        return False

def install_dependencies():
    """Install all required dependencies"""
    print("📦 Installing dependencies...")
    
    # Upgrade pip first
    print("⬆️  Upgrading pip...")
    subprocess.run([sys.executable, "-m", "pip", "install", "--upgrade", "pip"])
    
    # Install PyTorch with CUDA
    print("🔥 Installing PyTorch with CUDA 12.1...")
    torch_cmd = [
        sys.executable, "-m", "pip", "install",
        "torch", "torchvision", "torchaudio", 
        "--index-url", "https://download.pytorch.org/whl/cu121"
    ]
    result = subprocess.run(torch_cmd)
    
    if result.returncode != 0:
        print("⚠️  CUDA PyTorch failed, installing CPU version...")
        subprocess.run([sys.executable, "-m", "pip", "install", "torch", "torchvision", "torchaudio"])
    
    # Install other dependencies
    dependencies = [
        "transformers>=4.35.0",
        "sentence-transformers>=2.2.2", 
        "qdrant-client>=1.6.0",
        "rank-bm25>=0.2.2",
        "pypdf>=3.0.0",
        "requests>=2.25.0",
        "rich>=13.0.0",
        "tqdm>=4.62.0",
        "numpy>=1.21.0",
        "pandas>=1.3.0",
        "scikit-learn>=1.3.0",
        "accelerate>=0.24.0"
    ]
    
    print("📚 Installing additional packages...")
    for dep in dependencies:
        print(f"  Installing {dep}...")
        subprocess.run([sys.executable, "-m", "pip", "install", dep])
    
    print("✅ Dependencies installed!")

def setup_directories():
    """Create necessary directories"""
    print("📁 Setting up directories...")
    
    dirs = ["data", "logs", "models", "output"]
    for dir_name in dirs:
        Path(dir_name).mkdir(exist_ok=True)
        print(f"✅ Created: {dir_name}/")

def check_ollama():
    """Check Ollama installation and LLaMA 3 8B model"""
    print("🦙 Checking Ollama and LLaMA 3 8B...")
    
    # Check if ollama command exists
    try:
        result = subprocess.run(["ollama", "--version"], capture_output=True, text=True)
        if result.returncode == 0:
            print("✅ Ollama installed")
            
            # Check if LLaMA 3 8B is available
            result = subprocess.run(["ollama", "list"], capture_output=True, text=True)
            if "llama3:8b" in result.stdout:
                print("✅ LLaMA 3 8B model found")
                return True
            else:
                print("⚠️  LLaMA 3 8B model not found")
                print("💡 Run: ollama pull llama3:8b")
                return False
        else:
            print("❌ Ollama command failed")
            return False
    except FileNotFoundError:
        print("❌ Ollama not installed")
        print("💡 Install from: https://ollama.com/download")
        return False

def create_config_file():
    """Create configuration file"""
    print("⚙️  Creating configuration...")
    
    config_content = '''# LLaMA 3 8B Medical RAG Configuration
# Auto-generated by setup script

MODEL_NAME = "llama3:8b"
OLLAMA_URL = "http://localhost:11434"
EMBEDDING_MODEL = "BAAI/bge-large-en-v1.5"
BATCH_SIZE = 64  # GPU optimized
CONTEXT_LENGTH = 4096
MAX_TOKENS = 2048
TEMPERATURE = 0.1  # Medical accuracy
'''
    
    with open("config.ini", "w") as f:
        f.write(config_content)
    
    print("✅ Configuration created: config.ini")

def test_system():
    """Test the complete system"""
    print("🧪 Testing system components...")
    
    try:
        # Test imports
        print("  Testing imports...")
        import torch
        from sentence_transformers import SentenceTransformer
        import requests
        print("  ✅ All imports successful")
        
        # Test CUDA
        if torch.cuda.is_available():
            print(f"  ✅ CUDA available: {torch.cuda.get_device_name(0)}")
        else:
            print("  ⚠️  CUDA not available")
        
        # Test Ollama connection
        print("  Testing Ollama connection...")
        try:
            response = requests.get("http://localhost:11434/api/version", timeout=5)
            if response.status_code == 200:
                print("  ✅ Ollama server running")
                
                # Test LLaMA 3 8B
                models_response = requests.get("http://localhost:11434/api/tags", timeout=5)
                if models_response.status_code == 200:
                    models = models_response.json().get("models", [])
                    llama_found = any("llama3:8b" in model.get("name", "") for model in models)
                    if llama_found:
                        print("  ✅ LLaMA 3 8B available")
                    else:
                        print("  ⚠️  LLaMA 3 8B not found")
                else:
                    print("  ❌ Cannot list Ollama models")
            else:
                print("  ❌ Ollama server not responding")
        except:
            print("  ❌ Ollama connection failed")
        
        return True
        
    except Exception as e:
        print(f"  ❌ System test failed: {e}")
        return False

def main():
    """Main setup function"""
    print_header()
    
    # Step 1: Check Python
    if not check_python_version():
        print("❌ Setup failed: Incompatible Python version")
        return
    
    # Step 2: Setup directories
    setup_directories()
    
    # Step 3: Install dependencies
    install_dependencies()
    
    # Step 4: Check CUDA after installation
    check_cuda()
    
    # Step 5: Check Ollama and model
    ollama_ready = check_ollama()
    
    # Step 6: Create config
    create_config_file()
    
    # Step 7: Test system
    system_working = test_system()
    
    # Final status
    print("\n" + "="*70)
    print("🏁 SETUP COMPLETE")
    print("="*70)
    
    if system_working:
        print("✅ System Status: READY")
        print("🦙 LLaMA 3 8B Medical RAG System is ready to use!")
        print()
        print("🚀 Quick Start Commands:")
        print("  python config_8b.py           # Test configuration")
        print("  python main_8b.py --8b-test   # Test LLaMA 3 8B")
        print("  python main_8b.py --index --interactive  # Start system")
        
        if ollama_ready:
            print("\n🎉 Everything is ready! You can start using the system now.")
        else:
            print("\n⚠️  Note: Start Ollama server first: ollama serve")
            print("💡 Download LLaMA 3 8B: ollama pull llama3:8b")
    else:
        print("⚠️  System Status: PARTIAL")
        print("Some components may need manual configuration.")
    
    print()
    print("📖 For help, check the README or run: python main_8b.py --help")

if __name__ == "__main__":
    main()